# teletext-twitter - creates pages for vbit2 teletext system
# (c) Mark Pentler 2018 (https://github.com/mpentler)
# see README.md for details on getting it running or run with -h
# output module

from processor import *
import time

# define our control codes here for easy use later
ESCAPE = chr(27)
DOUBLE_HEIGHT = ESCAPE + chr(77)
SET_BACKGROUND = ESCAPE + chr(93)
TWITTER_BIRD = chr(41) + chr(108) + chr(39)
text_colours = {"red" : 65, "green" : 66, "yellow" : 67 , "blue" : 68, "magenta" : 69, "cyan" : 70, "white" : 71}
mosaic_colours = {"red" : 81, "green" : 82, "yellow" : 83, "blue" : 84, "magenta" : 85, "cyan" : 86, "white" : 87}

def write_tweet_info(file, line_num, username, timestamp, config):
    string = "OL," + str(line_num) + ","
    string += "`" * (35-len(timestamp)-len(username))
    string += ESCAPE + chr(text_colours[config["username_colour"]]) +"@" + username
    string += ESCAPE + chr(text_colours["white"]) + "|"
    string += ESCAPE + chr(text_colours[config["timestamp_colour"]]) + timestamp
    string += "\r\n"
    file.write(string)

def write_tweet_line(file, line_num, line, config):
    string = "OL," + str(line_num) + ","
    string += ESCAPE + chr(text_colours[config["tweet_colour"]]) + line
    string += "\r\n"
    file.write(string)

def write_header(file, subpage, max_subpages, config): # write a header for the page and pop a nice banner at the top
    page_title = config["page_title"] + " " + "{:02d}/{:02d}".format(subpage, max_subpages)
    logo_spacer = " " * (39 - (4 + len(page_title) + 5))
    if subpage == 1: # we only want these lines once
        file.write("DE,Autogenerated by Teletext-Twitter\r\n")
        file.write("PS,8000\r\n")
        file.write("CT," + str(config["cycle_time"]) + ",T\r\n")
    file.write("PN," + str(config["page_number"]) + "{:02}\r\n".format(subpage))
    file.write("SC,00" + "{:02}\r\n".format(subpage))
    file.write("OL,1," + ESCAPE + chr(text_colours[config["header_colour"]]) + SET_BACKGROUND +
               DOUBLE_HEIGHT + ESCAPE + chr(text_colours[config["page_title_colour"]]) + page_title +
               logo_spacer + ESCAPE + chr(mosaic_colours["cyan"]) + TWITTER_BIRD + "\r\n")
    file.write("OL,3," + ESCAPE + chr(mosaic_colours[config["header_separator"]]) + (chr(35) * 39) + "\r\n")

def write_ehancements(file, enhancements):
    for p in range(15): # up to 15 enhancement packets per subpage
        packet = "OL,26," + chr(0x40 + p) # first byte is designation code
        for e in range(13): # up to 13 triplets per enhancement packet
            if len(enhancements) > p*13+e:
                # combine parts of enhancement data into an 18 byte triplet, then slice it up into three 6 byte values to write to the row with bit 6 set
                triplet = enhancements[p*13+e][0] | ((enhancements[p*13+e][1]) << 6) | ((enhancements[p*13+e][2]) << 11)
                packet+=chr(0x40+(triplet&0x3F))+chr(0x40+((triplet>>6)&0x3F))+chr(0x40+((triplet>>12)&0x3F))
            elif e == 0:
                # TODO: generate packet of terminators if previous packet is full.
                return
            else:
                packet+=chr(0x7f)+chr(0x7f)+chr(0x7f)
        file.write(packet+"\r\n")

def write_tweets(twitter_object, mode, count, config, query=None): # grab the latest timeline
    if mode == "home":
        statuses = twitter_object.GetHomeTimeline(count=count)
    elif mode == "search":
        statuses = twitter_object.GetSearch(term=query, result_type="recent", count=count)
    elif mode == "user":
        statuses = twitter_object.GetUserTimeline(screen_name=query, count=count)

    filename = config["tti_path"] + "P" + str(config["page_number"]) + ".tti"
    subpage = 1

    # pre-calculate how many subpages we're going to
    # write - is there a better way of doing this?
    line_position = 4
    for status in statuses:
        tweet_text = tweet_remove_emojis(status.text)
        tweet_text = tweet_remove_urls(tweet_text)
        if mode == "search":
            tweet_text = tweet_highlight_query(tweet_text, query, config)
        tweet_text = charsub(tweet_text)
        tweet_text = textwrap.wrap(tweet_text, 38)
        post_length = len(tweet_text) + 1
        if (line_position + post_length) > 24:
            subpage += 1
            if subpage > 99:
                break # reached subpage limit - no point checking the rest
            line_position = 4
        line_position += post_length
    max_subpages = min(subpage, 99)

    # reset everything for the actual writing
    subpage = 1
    with open(filename, "w+", newline="") as file:
        write_header(file, subpage, max_subpages, config)
    line_position = 4
    subpage_enhancements = []

    for status in statuses: # iterate through our responses
        tweet_text = tweet_remove_emojis(status.text)
        tweet_text = tweet_remove_urls(tweet_text)
        if mode == "search":
            tweet_text = tweet_highlight_query(tweet_text, query, config)
        tweet_text = charsub(tweet_text)
        tweet_text = textwrap.wrap(tweet_text, 38) # make sure our lines fit on the screen
        tweet_time = time.strptime(status.created_at,"%a %b %d %H:%M:%S +0000 %Y")
        tweet_human_time = time.strftime("%d-%b-%Y %H:%S", tweet_time) # reformat time/date output
        tweet_username = charsub(status.user.screen_name)

        with open(filename, "a", newline="") as file:
            post_length = len(tweet_text) + 1 # how long is our next tweet? (including info line)
            if (line_position + post_length) > 24: # are we about to go over the page?
                file.write("FL,0,0,0,0,0,100\r\n")
                if subpage_enhancements:
                    write_ehancements(file, subpage_enhancements)
                subpage += 1 # start a new page
                subpage_enhancements = []
                if subpage > 99:
                    return # reached subpage limit - dump the rest
                write_header(file, subpage, max_subpages, config)
                line_position = 4 # and reset our cursor
            tweet_username_enhanced = charenhance(tweet_username,(37-len(tweet_human_time)-len(tweet_username)))
            if tweet_username_enhanced[1]:
                subpage_enhancements.append([line_position+40,4,0]) # active position to start of row
                subpage_enhancements += tweet_username_enhanced[1]
            write_tweet_info(file, line_position, tweet_username_enhanced[0], tweet_human_time, config)
            line_position += 1
            for line in tweet_text:
                tweet_text_line = charenhance(line,1)
                if tweet_text_line[1]:
                    subpage_enhancements.append([line_position+40,4,0]) # active position to start of row
                    subpage_enhancements += tweet_text_line[1]
                write_tweet_line(file, line_position, tweet_text_line[0], config)
                line_position += 1
    
    # finish the last subpage
    with open(filename, "a", newline="") as file:
        file.write("FL,0,0,0,0,0,100\r\n")
        if subpage_enhancements:
            write_ehancements(file, subpage_enhancements)
